#!/bin/bash
set -e

mkdir -p ~/venv
python3 -m venv ~/venv
source ~/venv/bin/activate
sudo apt-get update
sudo apt-get install -y git python3-dev libffi-dev gcc libssl-dev libdbus-glib-1-dev
sudo apt-get install -y python3-venv
python -m ensurepip --upgrade
python -m pip install --upgrade pip
if [ -d "kolla-ansible" ]; then
    echo "kolla-ansible directory already exists, skipping git clone."
else
    cd ~/
    echo "Cloning kolla-ansible repository..."
    git clone https://opendev.org/openstack/kolla-ansible
fi
cd kolla-ansible
python -m pip install .
sudo mkdir -p /etc/kolla
sudo chown $USER:$USER /etc/kolla
sudo cp -r ~/venv/share/kolla-ansible/etc_examples/kolla/* /etc/kolla
kolla-ansible install-deps
cp ~/venv/share/kolla-ansible/ansible/inventory/all-in-one .
kolla-ansible bootstrap-servers -i ./all-in-one
kolla-ansible prechecks -i ./all-in-one
kolla-ansible deploy -i ./all-in-one
pip install python-openstackclient -c https://releases.openstack.org/constraints/upper/master
kolla-ansible post-deploy